name: bulk_finder
description: "Bulk Finder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter    
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_marker_popup: ^6.1.2
  geolocator: ^12.0.0
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2 # Untuk panggilan HTTP tambahan
  provider: ^6.1.2 # Untuk manajemen state
  cached_network_image: ^3.3.1 # Untuk gambar dari Supabase Storage
  flutter_rating_bar: ^4.0.1 # Untuk rating bintang
  intl: ^0.19.0 # Untuk format tanggal/waktu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/.env
  uses-material-design: true